# Generated by Django 3.0.5 on 2024-07-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20240701_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='medicineCost',
            new_name='appointmentFee',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='roomCharge',
        ),
    ]
