# Generated by Django 3.0.5 on 2024-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20240701_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprescribedetails',
            name='p_status',
            field=models.BooleanField(default=False),
        ),
    ]
